{% set name = "sisl" %}
{% set version = "0.9.5" %}
{% set sha256 = "ce740c2329415343ed3680164bd3bf9bd652d2284caaf6b12aa86eceb3e624bb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zerothi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - libblas
    - libcblas
    - python
    - six
    - numpy >=1.13.0
    - scipy
    - setuptools
  run:
    - libgfortran-ng >=3.0  # [osx]
    - libgfortran-ng >=4.9  # [linux]
    - python
    - six
    - pyparsing
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - netcdf4

test:
  requires:
    - pytest
  imports:
    - sisl
    - sisl.io

about:
  home: http://github.com/zerothi/sisl
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'Python tight binding toolbox with interoperability with DFT codes for large-scale transmission calculations'
  description: |
    sisl is a simple, easy to use toolbox for creating tight-binding
    electronic/phononic structures and/or post-process DFT output.
  doc_url: http://sisl.readthedocs.io/
  dev_url: https://github.com/zerothi/sisl

extra:
  recipe-maintainers:
    - zerothi
