{% set name = "sisl" %}
{% set version = "0.9.8" %}
{% set sha256 = "7873e251c1a3f33e80ed1b87043800e59614a5e09a1c5d7a19f2ce289524c946" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zerothi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - libcblas
    - liblapack
    - python
    - setuptools
    - six
    # once we hit 1.16.3 it should be fine again
    # I read that numpy-devel should work, so...
    - numpy <=1.15.3
    - scipy >=0.18
    - pyparsing
    - netcdf4
  run:
    - liblapack
    - python
    - six
    - pyparsing
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - netcdf4

test:
  requires:
    - pytest
  imports:
    - sisl
    - sisl.io

about:
  home: http://github.com/zerothi/sisl
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'Toolbox for electronic structure calculations and large scale transport'
  description: |
    sisl is a tool to manipulate density functional
    theory code input and/or output. It also implements tight-binding
    tools to create and manipulate multi-orbital (non)-orthogonal basis sets.
  doc_url: http://sisl.readthedocs.io/
  dev_url: https://github.com/zerothi/sisl

extra:
  recipe-maintainers:
    - zerothi
