{% set name = "sisl" %}
{% set version = "0.9.2" %}
{% set sha256 = "29f995077180dc43d30b6c55a2e933182912661d8ed8cfaf3f4c4ac40306fe91" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zerothi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - six  # [py27]
    - numpy
    - scipy
    - setuptools
  run:
    - libgfortran-ng >=3.0  # [osx]
    - libgfortran-ng >=4.9  # [linux]
    - python
    - six  # [py27]
    - numpy
    - netcdf4
    - scipy

test:
  requires:
    - pytest

about:
  home: http://github.com/zerothi/sisl
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'Python tight binding toolbox with interoperability with DFT codes for large-scale transmission calculations'
  description: |
    sisl is a simple, easy to use toolbox for creating tight-binding
    electronic/phononic structures and/or post-process DFT output.
  doc_url: http://sisl.readthedocs.io/
  dev_url: https://github.com/zerothi/sisl

extra:
  recipe-maintainers:
    - zerothi
