{% set name = "sisl" %}
{% set version = "0.11.0" %}
{% set sha256 = "23dc2f91143921fb2b2c772e6ff59807163c22f03c00fcf018c8f51aefb02494" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zerothi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - libcblas
    - liblapack
    - python
    - setuptools
    # once we hit 1.16.3 it should be fine again
    # I read that numpy-devel should work, so...
    - numpy <=1.15.3|>=1.16.3
    - scipy >=0.18
    # For cythonizing stuff
    - cython
    - pyparsing
    - netcdf4
  run:
    - liblapack
    - python
    - pyparsing
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - netcdf4
  run_constrained:
    - dill >=0.3.2
    - xarray >=0.10.0

test:
  requires:
    - pytest
  imports:
    - sisl
    - sisl.io

about:
  home: https://github.com/zerothi/sisl
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Toolbox for electronic structure calculations and large scale transport
  description: |
    sisl is a tool to manipulate density functional
    theory code input and/or output. It also implements tight-binding
    tools to create and manipulate multi-orbital (non)-orthogonal basis sets.
  doc_url: https://zerothi.github.io/sisl
  dev_url: https://github.com/zerothi/sisl

extra:
  recipe-maintainers:
    - zerothi
