{% set name = "sisl" %}
{% set version = "0.12.1" %}
{% set sha256 = "5e29c3a7a2e44c560b58a81895a7ddd2be825a58271c15fd8bea3c254983e08f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zerothi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/remove_oldest_numpy.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - setuptools
    - libblas
    - libcblas
    - liblapack
    - python
    - cython
    # this is for the sisl requirement
    - numpy >=1.13
    # this is for conda-smithy so that the global
    # pinning is correctly specified
    - numpy
    - scipy >=0.18
    - netcdf4
    - wheel
    - setuptools_scm
    - pyparsing >=1.5.7
  run:
    - python
    - pyparsing >=1.5.7
    - {{ pin_compatible('numpy') }}
    - scipy >=0.18
    - tqdm
    - netcdf4
  run_constrained:
    - dill >=0.3.2
    - xarray >=0.10.0

test:
  requires:
    - pytest
  imports:
    - sisl
    - sisl.io
    - sisl.io.siesta._siesta
    - sisl.geom
    - sisl.linalg
    - sisl.mixing
    - sisl.physics
    - sisl.shape
    - sisl.unit
    - sisl.utils

about:
  home: https://github.com/zerothi/sisl
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Toolbox for electronic structure calculations and large scale transport
  description: |
    sisl is a tool to manipulate density functional
    theory code input and/or output. It also implements tight-binding
    tools to create and manipulate multi-orbital (non)-orthogonal basis sets.
  doc_url: https://zerothi.github.io/sisl
  dev_url: https://github.com/zerothi/sisl

extra:
  recipe-maintainers:
    - zerothi
