{% set name = "sisl" %}
{% set version = "0.15.2" %}
{% set sha256 = "762a13a1d4a4d09c2c9b3495c537c66689a786e8b28d42136f95b2c01f58588b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zerothi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]
  skip: true  # [py<39]

requirements:
  build:
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    # The below python packages are necessary for cross-compilation
    - python  # [build_platform != target_platform ]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform ]
    - cython >=3  # [build_platform != target_platform ]
    - numpy >=2.0.0rc1  # [build_platform != target_platform ]
  host:
    - libblas
    - libcblas
    - liblapack
    - python
    - pip
    - pyproject-metadata
    - setuptools_scm  >=6.2
    - scikit-build-core >=0.8
    - cython >=3
    # a build problem occurs with 1.22.* (infinite recursion on module creation)
    - numpy >=2.0.0rc1
  run:
    - python
    - pyparsing >=2.2.1
    - numpy >=1.21
    - scipy >=1.6
    - tqdm >=4.36
    - xarray >=0.21
    - netcdf4
  run_constrained:
    - dill >=0.3.2

test:
  requires:
    - pytest
    - matplotlib
    - plotly
    - scikit-image
  imports:
    - sisl
    - sisl.io
    - sisl.io.siesta._siesta
    - sisl.geom
    - sisl.linalg
    - sisl.mixing
    - sisl.physics
    - sisl.shape
    - sisl.unit
    - sisl.utils

about:
  home: https://github.com/zerothi/sisl
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Toolbox for electronic structure calculations and large scale transport
  description: |
    sisl is a tool to manipulate density functional
    theory code input and/or output. It also implements tight-binding
    tools to create and manipulate multi-orbital (non)-orthogonal basis sets.
  doc_url: https://zerothi.github.io/sisl
  dev_url: https://github.com/zerothi/sisl

extra:
  recipe-maintainers:
    - zerothi
