{% set name = "sisl" %}
{% set version = "0.14.2" %}
{% set sha256 = "f805e4e748d911bae3a270ea286878f3c0ddfd986615844441f2bab6c4d459ae" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zerothi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/remove_oldest_numpy.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - python  # [build_platform != target_platform ]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform ]
    - cython >=0.29.28  # [build_platform != target_platform ]
    - numpy >1.22  # [build_platform != target_platform]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - python
    - pip
    - scikit-build-core
    - pyproject-metadata
    - setuptools_scm
    - cython >=0.29.28
    # a build problem occurs with 1.22.* (infinite recursion on module creation)
    - numpy >1.22
    - scipy >=1.5.0
    - netcdf4
    - pyparsing >=1.5.7
  run:
    - python
    - pyparsing >=1.5.7
    - {{ pin_compatible('numpy') }}
    - scipy >=1.5.0
    - tqdm
    - xarray >=0.10.0
    - netcdf4
      #- vc 14  # [win]
  run_constrained:
    - dill >=0.3.2

test:
  requires:
    - pytest
    - matplotlib
    - plotly
    - scikit-image
  imports:
    - sisl
    - sisl.io
    - sisl.io.siesta._siesta
    - sisl.geom
    - sisl.linalg
    - sisl.mixing
    - sisl.physics
    - sisl.shape
    - sisl.unit
    - sisl.utils

about:
  home: https://github.com/zerothi/sisl
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Toolbox for electronic structure calculations and large scale transport
  description: |
    sisl is a tool to manipulate density functional
    theory code input and/or output. It also implements tight-binding
    tools to create and manipulate multi-orbital (non)-orthogonal basis sets.
  doc_url: https://zerothi.github.io/sisl
  dev_url: https://github.com/zerothi/sisl

extra:
  recipe-maintainers:
    - zerothi
