{% set name = "sisl" %}
{% set version = "0.9.4" %}
{% set sha256 = "81d3e12f855bc824ee6bc9bedc26ab8d6a51d5d8fa9d8f0e8fe28b07a424aed3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zerothi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - six  # [py27]
    - numpy
    - scipy <=1.0.0
    - setuptools
  run:
    - libgfortran-ng >=3.0  # [osx]
    - libgfortran-ng >=4.9  # [linux]
    - python
    - six  # [py27]
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy', upper_bound='1.1.0') }}
    - netcdf4

test:
  requires:
    - pytest

about:
  home: http://github.com/zerothi/sisl
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'Python tight binding toolbox with interoperability with DFT codes for large-scale transmission calculations'
  description: |
    sisl is a simple, easy to use toolbox for creating tight-binding
    electronic/phononic structures and/or post-process DFT output.
  doc_url: http://sisl.readthedocs.io/
  dev_url: https://github.com/zerothi/sisl

extra:
  recipe-maintainers:
    - zerothi
