travis:
  secure:
    BINSTAR_TOKEN: PHnm/G0qY79/lXXQizlD7cFIjk+X9OvkYewt8BkInJKjPIyzI0YvPpq2wvPYWU2WNKMaaRmHpxd9LfaAwXvzsr6as/ts9HktrnL2U5/aXgNE5/jicSeU+RaXDFwnqLfDmE8KhcrwVf77SnKvq/oD+4LBZG4XJwfNrjppJeg3QOHqOEZPYIp6lBoflONKubyxXPKiOpmW3J7TCTsV/EcYzyZKeAzdigpaGGU4lPiKbZvHGtAeIZ41gUM4VOhlb+w0Dt5O33CMaLhGo/IxN7JCsvXBP+T2J4aKkWyaAYr/3mB9MD3d8nHmbWEEjg9driDkjZN20LsuFANTzD+XuMsOpEFbgUyhXq3DME9TuA0WbuHN4IVLj1oGNrwxm+zgDtDxZ3N7HqjGBUTfM5yLUJhGZy65mEvAk/j9erczmNSDhOYtArMw82wRlHrw44kBFOwro4yLUvZa92qGzpwwtGLSEyscFfoMgVPYKPWN+Psd+xYIMYvAVFPPR8HVH2GfNGwRZOD2p7KPWjo+H685TRTVzi5IfLFRcz6wulMsh22dohh8MccQlPxsFKZ6fqTQRsLgtuyQIrSMismNuhPeKIq7YQwT+Poy2IJvlILrWJEtZ30O5qvdGtiICIQsZM40xXbfGE20QwcUFlOHVzUekD8qCtuYFiERwZ+2tLPIjvGJ2ac=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
