appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: avX93Gyy3OEWM1MurwzO95XgvVHMWISXr2C08M4qlKrvhHeyssa4bYfwaFKFO0fVERloefUnY82qdMngWWdkhrQ6+n/t3EvAlhTY95usBgq4JJjb5G4BIbLOHS4xcaWHwsbB+BkwDyUrGA3dBobX6OCBUTR7iPQHGTT9NZgwSxEX0J21HhIPVObu1QvUDoq7wQn1Zm5q222Ui3tOW1yHDN8tAR3KXL6mafibmkLED++KQL2Th4yjJ7SO5MxZRem2UTH4+jyQlROmlJVfuyGAhDLUeHMTzArSfUoECrX8UcpL4Vdj2YU/FMsO7rasouhSo36OXecMKNCywr4cLzIXlHa/cgy0YA7Khpkt+hZaXhlQSu3U2/XlOGT9FJbttu5cwGtrL1QwmATvDClUEKNjXaphreH3scdPh2I4TjkcOrmZXQxo78zXweUDk3uiqb2qg43wuSI43aEVqkSNyidlCIq6CtyF3KzQ8pwXs27ajCVBSD7F+uU1NN9z31H6fhaj7HgK5WSB+vyY/DJkDMJY8H5brTYCAvHNVpIX7/z9EbSNygff3PR57EnhVmcLX6bbPLGimrBsWGMiUag5jzp/Kg+oQoREDeIHtQq4uAkdwUlrDbZV9cFSs7bZYZkAEb+euN6aQBkZx0VFf7znchI2M2n6wlQqBVrpw65SuWy6DWc=}
provider:
  win: azure
conda_forge_output_validation: true
